### ISSUE TITLE
Doesn't work as expected with babel-node

### ISSUE THREAD

**Issue by scottmas** [kentcdodds/babel-macros#30]
Using the latest babel-macros and node (everything pulled fresh), and the simple eval macro described in the [fixtures](https://github.com/kentcdodds/babel-macros/blob/master/src/__tests__/fixtures/eval.macro.js), `babel-node` blows up on a file that compiles just fine.

The following input file
```javascript
//input.js
import Eval from '../eval.macro'
console.log(Eval`1 + 1`);
```
generates the following output file (as expected) when running `babel input.js -o output.js`:
```javascript
//output.js
console.log(2)
```

So that the following command prints 2 to the console as expected
```bash
babel input.js -o output.js && node output.js
#prints 2
```
But babel-node blows up:
```bash
babel-node input.js

/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^
SyntaxError: /Users/Scott-mb/Projects/react-directive/consumer/index.js: /Users/Scott-mb/Projects/react-directive/.babelrc: Error while parsing JSON - Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
    at error (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:56:25)
    at word (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:393:13)
    at value (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:493:56)
    at Object.parse (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:508:18)
    at ConfigChainBuilder.addConfig (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
    at buildConfigChain (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at compile (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/Scott-mb/.nvm/versions/node/v8.4.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:14)
```

Any ideas what the issue could be?

**Comment by kentcdodds** [comment]
Thanks for the issue. I'm not sure what it could be. Could you dig a little deeper?

**Comment by scottmas** [comment]
Sure. Taking a look...

**Comment by scottmas** [comment]
Well, it has nothing to do with the eval macro. The simplest possible macro still blows up in the same way: 
```javascript
const {createMacro} = require('babel-macros');

module.exports = createMacro(({references, babel}) => {
  (references.default || []).forEach(reference => {
    reference.replaceWith(babel.types.stringLiteral('Sup foo!'))
  })
})
```

**Comment by scottmas** [comment]
It was just babel-node blowing up on a misconfigured .babelrc way up the chain. So nothing to do with the library. Sorry for the false alarm!
